### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by githubgist123** [GeniusRUS/MultiProgressBar#6]
Feature request:
Add stroke
Add resume method
Change height of MultiProgressBar
Change corner radius of progress

**Comment by GeniusRUS** [comment]
Thanks for these suggestions!
I will consider the implementation possibilities and make them

**Comment by githubgist123** [comment]
Also can you add duration for each progress?

**Comment by GeniusRUS** [comment]
@githubgist123 about the different duration of each progress cell - sorry, but I'm not sure if this is possible to do within the current implementation

This is because the display time of the cell is calculated linearly to properly work the `ValueAnimator` instance. As a possible solution, I can propose to track steps in the implementation of the `ProgressStepChangeListener` interface and set a new execution time for each step using the `setSingleDisplayTime` method, which was added in the last update, `1.1.0`

I would also like to ask you to clarify what you mean by
> Add resume method

Resuming the current progress is possible using the `start` method, if it was previously stopped using the `pause` method

**Comment by githubgist123** [comment]
I am working something like Instagram Stories. I use Glide library to download picture and I use methods start and pause for waiting downloading picture. When user press home button I want to pause progress. I attached method start to onAttach method of lifeCycle of Controller(Conductor framework something like fragment) and pause method to onDetach method of lifeCycle of Controller. When controller first time appear and progress start because onAttach method of Contolller called. Prevent this behaviour I added my own flag isStarted.

Also can you add something like public flag isPause?

**Comment by githubgist123** [comment]
Also can you add start from position N?

**Comment by GeniusRUS** [comment]
Added in release [1.4.0](https://github.com/GeniusRUS/MultiProgressBar/releases/tag/1.4.0)
